name: Run cucumber test

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup Java
      - uses: actions/setup-java@v3
        with:
          java-version: "19"
          cache: maven
          distribution: "temurin"

      # Install Chrome using Chocolatey (Windows package manager)
      - name: Install Chrome
        run: choco install googlechrome --no-progress -y

      # Run Maven tests
      - name: Run Tests
        run: mvn clean test
